# Generated by Django 5.1.1 on 2025-02-13 12:05

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('_id', models.CharField(db_column='_id', default=uuid.uuid1, editable=False, max_length=45, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, db_column='name', max_length=45, null=True)),
                ('desc', models.CharField(blank=True, db_column='desc', max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('_id', models.CharField(db_column='_id', default=uuid.uuid1, editable=False, max_length=45, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, db_column='name', max_length=45, null=True)),
                ('desc', models.CharField(blank=True, db_column='desc', max_length=250, null=True)),
            ],
            options={
                'db_table': 'main_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('_id', models.CharField(db_column='_id', default=uuid.uuid1, editable=False, max_length=45, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_column='name', max_length=45)),
                ('desc', models.CharField(db_column='desc', max_length=10000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('weight', models.CharField(max_length=100)),
                ('image', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('_id', models.CharField(db_column='_id', default=uuid.uuid1, editable=False, max_length=45, primary_key=True, serialize=False, unique=True)),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('product_availability_time', models.DateTimeField(blank=True, null=True)),
                ('product_quantity', models.CharField(blank=True, max_length=1000, null=True)),
                ('product_quality', models.CharField(blank=True, max_length=255, null=True)),
                ('product_certification', models.TextField(blank=True, null=True)),
                ('expected_price', models.CharField(blank=True, max_length=100, null=True)),
                ('product_image', models.TextField(blank=True, null=True)),
                ('product_video', models.TextField(blank=True, null=True)),
                ('geo_site', models.CharField(choices=[('MANDAL', 'M'), ('BLOCK', 'B'), ('VILLAGE', 'V'), ('DISTRICT', 'D'), ('STATE', 'S'), ('COUNTRY', 'C')], default='V', max_length=50)),
                ('desc', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], db_column='status', default='INACTIVE', max_length=50)),
            ],
            options={
                'db_table': 'seller_product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('_id', models.CharField(db_column='_id', default=uuid.uuid1, editable=False, max_length=45, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_column='name', max_length=45)),
                ('desc', models.CharField(db_column='desc', max_length=10000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sub_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('_id', models.CharField(db_column='_id', default=uuid.uuid1, editable=False, max_length=45, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_column='name', max_length=45)),
                ('capital', models.CharField(blank=True, db_column='capital', max_length=45, null=True)),
                ('alternativename', models.CharField(blank=True, db_column='alternativename', max_length=45, null=True)),
                ('desc', models.CharField(blank=True, db_column='desc', max_length=250, null=True)),
                ('type', models.CharField(blank=True, choices=[('COUNTRY', 'COUNTRY')], db_column='type', default='COUNTRY', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('continent_id', models.CharField(max_length=100)),
                ('image_location', models.TextField()),
                ('hindu_population', models.CharField(max_length=100)),
                ('overall_population', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'country',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('_id', models.CharField(db_column='_id', default=uuid.uuid1, editable=False, max_length=45, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_column='name', max_length=45)),
                ('shortname', models.CharField(db_column='shortname', max_length=45)),
                ('headquarters', models.CharField(blank=True, db_column='headquarters', max_length=45, null=True)),
                ('desc', models.CharField(blank=True, db_column='desc', max_length=250, null=True)),
                ('cityname', models.CharField(max_length=200)),
                ('created_at', models.CharField(max_length=200)),
                ('type', models.CharField(blank=True, choices=[('DISTRICT', 'DISTRICT'), ('CITY', 'CITY')], db_column='type', default='DISTRICT', max_length=30)),
            ],
            options={
                'db_table': 'district',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.CharField(db_column='id', default=uuid.uuid1, editable=False, max_length=45, primary_key=True, serialize=False)),
                ('verification_otp', models.CharField(blank=True, max_length=6, null=True)),
                ('verification_otp_created_time', models.DateTimeField(null=True)),
                ('verification_otp_resend_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('CREATED', 'CREATED'), ('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='CREATED', max_length=50)),
                ('full_name', models.CharField(blank=True, db_column='full_name', max_length=45, null=True)),
                ('surname', models.CharField(blank=True, db_column='surname', max_length=100, null=True)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHER', 'OTHER')], default='MALE', max_length=50)),
                ('age', models.CharField(max_length=100, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('id_type', models.CharField(blank=True, choices=[('AADHAR', 'Aadhar'), ('PAN', 'PAN'), ('VOTER_ID', 'Voter ID'), ('DRIVING_LICENSE', 'Driving License')], max_length=50, null=True)),
                ('id_number', models.CharField(blank=True, max_length=50, null=True)),
                ('id_proof', models.TextField(blank=True, null=True)),
                ('stakeholder_type', models.CharField(choices=[('NONE', 'NONE'), ('SELLER', 'SELLER'), ('BUYER', 'BUYER'), ('SELLER_AND_BUYER', 'SELLER_AND_BUYER'), ('MARKETING_EXECUTIVE', 'MARKETING_EXECUTIVE')], default='NONE', max_length=50)),
                ('highest_education_qualification', models.CharField(blank=True, choices=[('10th Class', 'CLASS_10'), ('Intermediate', 'INTERMEDIATE'), ('Graduate', 'GRADUATE'), ('Post Graduate', 'POST_GRADUATE')], default='10th Class', max_length=50, null=True)),
                ('is_working_professional', models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=3, null=True)),
                ('years_of_work_experience', models.IntegerField(blank=True, null=True)),
                ('resume', models.TextField(blank=True, null=True)),
                ('is_member', models.CharField(choices=[('true', 'true'), ('false', 'false')], default='false', max_length=50)),
                ('account_type', models.CharField(max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('family_images', models.JSONField(blank=True, default=list)),
                ('groups', models.ManyToManyField(blank=True, related_name='register_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='register_user_permissions', to='auth.permission')),
            ],
            options={
                'db_table': 'user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('_id', models.CharField(db_column='_id', default=uuid.uuid1, editable=False, max_length=45, primary_key=True, serialize=False, unique=True)),
                ('quantity', models.IntegerField(db_column='quantity', default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True, db_column='added_at')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='hindu.product')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cart',
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('_id', models.CharField(db_column='_id', default=uuid.uuid1, editable=False, max_length=45, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_column='name', max_length=45)),
                ('municipality', models.CharField(blank=True, db_column='municipality', max_length=45, null=True)),
                ('population', models.CharField(blank=True, db_column='population', max_length=45, null=True)),
                ('desc', models.CharField(db_column='desc', max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(blank=True, choices=[('BLOCK', 'BLOCK'), ('TOWN', 'TOWN')], db_column='type', default='BLOCK', max_length=30)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='hindu.district')),
            ],
            options={
                'db_table': 'block',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('_id', models.CharField(db_column='_id', default=uuid.uuid1, editable=False, max_length=45, primary_key=True, serialize=False, unique=True)),
                ('review_text', models.TextField(db_column='review_text')),
                ('rating', models.IntegerField(db_column='rating')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='hindu.product')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('_id', models.CharField(db_column='_id', default=uuid.uuid1, editable=False, max_length=45, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_column='name', max_length=45)),
                ('shortname', models.CharField(db_column='shortname', max_length=45)),
                ('capital', models.CharField(blank=True, db_column='capital', max_length=45, null=True)),
                ('desc', models.CharField(blank=True, db_column='desc', max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(blank=True, choices=[('STATE', 'STATE')], db_column='type', default='STATE', max_length=30)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='hindu.country')),
            ],
            options={
                'db_table': 'state',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='hindu.state'),
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('_id', models.CharField(db_column='_id', default=uuid.uuid1, editable=False, max_length=45, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_column='name', max_length=45)),
                ('desc', models.CharField(blank=True, db_column='desc', default=None, max_length=500, null=True)),
                ('mapUrl', models.URLField(blank=True, db_column='map_url', max_length=255, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], db_column='status', default='INACTIVE', max_length=50)),
                ('pin_code', models.CharField(db_column='pin_code', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image_location', models.CharField(blank=True, max_length=500, null=True)),
                ('type', models.CharField(blank=True, choices=[('VILLAGE', 'VILLAGE'), ('AREA', 'AREA')], db_column='type', default='VILLAGE', max_length=30)),
                ('old_village_code', models.CharField(db_column='old_village_code', max_length=45, null=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villages', to='hindu.block')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='villages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'village',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='object_id',
            field=models.ForeignKey(blank=True, db_column='object_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='hindu.village'),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('_id', models.CharField(db_column='_id', default=uuid.uuid1, editable=False, max_length=45, primary_key=True, serialize=False, unique=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to='hindu.product')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wishlist',
                'unique_together': {('product', 'user')},
            },
        ),
    ]
